### ISSUE TITLE
Download controller wrongly serves file content as text

### ISSUE THREAD

**Issue by mnl-zmr** [grails-file-uploader/grails-file-uploader#2]
In DownloadController::index the file saved on disk is served by outputting the text property from the file object. This works with text based files (HTML, XML, ...), but not with binary data. To correctly serve a binary stream you can use an InputStream:

response.outputStreamfile << file.newInputStream()

**Comment by lucastex** [comment]
Hello der-tale,

can you correct it and send a pull request?
